welcomeGroup = """\
Приветствую вас в таверне города Крезар, Искатели! \
Присаживайтесь за стол, заказывайте выпить, чувствуйте себя как дома.
"""
chooseLanguage = "Выберите язык:"
onlyAdminLanguage = "Данное действие доступно только администраторам."
internalError = "Произошла ошибка, попробуйте позже."
profileTemplate = """\
${personage_icon_with_name}
${money_icon}Золото: ${personage_money}"""

# текста для группы
groupStats = """\
📊<b>Статистика группы:</b>

🗡Успешные рейды: ${raids_count}
🤺Завершено дуэлей: ${duels_count}

🍻Потрачено в тавернe: ${money_icon}${tavern_money_spent}
"""

# текста для лички
# TODO перенести куда-нибудь
welcomeUser = "Добро пожаловать в таверну, Искатель!"
receptionDesk = "Здравствуй! Чем могу помочь?"
mainMenu = [
    "Располагайся поудобнее, не торопись."
]
